name: Build/release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  build-interface:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: zip
        run: zip -r CC_RC.zip dist
      - name: Create Release with artifacts
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "${GITHUB_REF#refs/tags/}"
          files: |
            ${{github.workspace}}/dist/CC_RC.zip
